# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :release do |options|
    version = options.fetch(:version, "undefined")
    if version == "undefined"
      UI.user_error!("Missing version number, append ` version:X.Y.Z`")
    end

    podspec_version = version_get_podspec(path: "Confy.podspec")
    if podspec_version != version
      version_bump_podspec(path: "Confy.podspec", version_number: version)
      commit_version_bump
    end

    github_release = set_github_release(
      repository_name: "fastlane/fastlane",
      api_token: ENV["CONFY_RELEASE_TOKEN"],
      name: "New release",
      tag_name: version,
      description: "No changelog yet",
      commitish: "main",
      upload_assets: []
    )
    # add actions here: https://docs.fastlane.tools/actions
  end
end
